spring:
    application:
        name: globalstatistic
    datasource:
        url: jdbc:postgresql://globalstatistic-postgres:5432/globalstatistic
        username: globalstatistic
        password: password
    kafka:
        bootstrap-servers: kafka:9092
        client-id: globalstatistic-producer
        consumer:
            bootstrap-servers: kafka:9092
            group-id: globalstatistic-group
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
    data:
        redis:
            database: 0
            host: globalstatistic-redis
            port: 6379
