spring:
    application:
        name: globalstatistic
    datasource:
        url: jdbc:postgresql://globalstatistic-postgres:5432/globalstatistic
        username: globalstatistic
        password: password
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
