spring:
    application:
        name: localstatistic
    datasource:
        url: jdbc:postgresql://localstatistic-postgres:5432/localstatistic
        username: localstatistic
        password: password
    kafka:
        bootstrap-servers: kafka:9092
        client-id: localstatistic-producer
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
    data:
        redis:
            database: 0
            host: localstatistic-redis
            port: 6379
